### ISSUE TITLE
Feature article : create main banner component

### ISSUE THREAD

**Issue by jaesukpark77** [marketkarly-team/marketkarly-client#8]
### Purpose
- It's use for MAIN page
- It's for advertisement banner
- Swiper.js is used for swipping pages

### Image
![Image](https://user-images.githubusercontent.com/73949086/215710170-cee9760a-fab2-4437-b1d8-097700ffb22e.png)

**Comment by realldk** [comment]
advertisement가 광고 차단에 걸리는 키워드라 main banner로 바꾸겠습니다.
